### ISSUE TITLE
Ignore dev specific setup

### ISSUE THREAD

**Issue by aldnav** [boredchinese/election-app#1]
Please ignore and/or remove the following for being tracked:

- db.sqlite3
- env/

**Comment by aldnav** [comment]
This is useful as well https://www.gitignore.io/api/django

**Comment by aldnav** [comment]
One last thing, do this on a separate branch and make a pull request when the updates are ready. Don't forget to reference this issue in your pull request message/comment.

**Comment by ephraimeg** [comment]
Should I use the template provided by github or would that be too much?

**Comment by aldnav** [comment]
@ephraimeg yes you can use it

**Comment by aldnav** [comment]
Resolved in https://github.com/boredchinese/election-app/pull/3.
